---
### group_vars/CONNECTED_ENDPOINTS.yml

# Definition of connected endpoints in the fabric.
servers:
  # Name of the defined server.
  - name: dc01-leaf-01-server1
    # Definition of adapters on the server.
    adapters:
      # Name of the server interfaces that will be used in the description of each interface
      - endpoint_ports: [ PCI1, PCI2 ]
        # Device ports where the server ports are connected.
        switch_ports: [ Ethernet5, Ethernet5 ]
        # Device names where the server ports are connected.
        switches: [ dc01-leaf-01a, dc01-leaf-01b ]
        # VLANs that will be configured on these ports.
        vlans: 11-12,21-22
        # Native VLAN to be used on these ports.
        native_vlan: 4092
        # L2 mode of the port.
        mode: trunk
        # Spanning tree portfast configuration on this port.
        spanning_tree_portfast: edge
        # Definition of the pair of ports as port channel.
        port_channel:
          # Optionally override the description of the port channel interface.
          description: PortChannel dc01-leaf-01-server1
          # Port channel mode for LACP.
          mode: active

  - name: dc01-bsl-01-server1
    adapters:
      - endpoint_ports: [ PCI1, PCI2 ]
        switch_ports: [ Ethernet5, Ethernet5 ]
        switches: [ dc01-bsl-01a, dc01-bsl-01b ]
        vlans: 11-12,21-22
        native_vlan: 4092
        mode: trunk
        spanning_tree_portfast: edge
        port_channel:
          mode: active

  # Start of definitions for DC2 (identical to DC1)

  # Name of the defined server.
  - name: dc02-leaf-01-server1
    # Definition of adapters on the server.
    adapters:
      # Name of the server interfaces that will be used in the description of each interface
      - endpoint_ports: [ PCI1, PCI2 ]
        # Device ports where the server ports are connected.
        switch_ports: [ Ethernet5, Ethernet5 ]
        # Device names where the server ports are connected.
        switches: [ dc02-leaf-01a, dc02-leaf-01b ]
        # VLANs that will be configured on these ports.
        vlans: 11-12,21-22
        # Native VLAN to be used on these ports.
        native_vlan: 4092
        # L2 mode of the port.
        mode: trunk
        # Spanning tree portfast configuration on this port.
        spanning_tree_portfast: edge
        # Definition of the pair of ports as port channel.
        port_channel:
          # The port-channel name on the endpoint that will be used in the port-channel description.
          endpoint_port_channel: Bond1
          # Port channel mode for LACP.
          mode: active

  - name: dc02-bsl-01-server1
    adapters:
      - endpoint_ports: [ PCI1, PCI2 ]
        switch_ports: [ Ethernet5, Ethernet5 ]
        switches: [ dc02-bsl-01a, dc02-bsl-01b ]
        vlans: 11-12,21-22
        native_vlan: 4092
        mode: trunk
        spanning_tree_portfast: edge
        port_channel:
          mode: active
