---
### group_vars/DC2.yml

# Default gateway used for the management interface
mgmt_gateway: 172.20.20.1

# Spine switch group
spine:
  # Definition of default values that will be configured to all nodes defined in this group
  defaults:
    # Set the relevant platform as each platform has different default values in Ansible AVD
    platform: cEOS
    # Pool of IPv4 addresses to configure interface Loopback0 used for BGP EVPN sessions
    loopback_ipv4_pool: 10.255.128.0/27
    # ASN to be used by BGP
    bgp_as: 65200

  # Definition of nodes contained in this group.
  # Specific configuration of device must take place under the node definition. Each node inherits all values defined under 'defaults'
  nodes:
    # Name of the node to be defined (must be consistent with definition in inventory)
    - name: dc02-spine-01
      # Device ID definition. An integer number used for internal calculations (ie. IPv4 address of the loopback_ipv4_pool among others)
      id: 11
      # Management IP to be assigned to the management interface
      mgmt_ip: 172.20.20.20/24

    - name: dc02-spine-02
      id: 12
      mgmt_ip: 172.20.20.21/24

# L3 Leaf switch group
l3leaf:
  defaults:
    # Set the relevant platform as each platform has different default values in Ansible AVD
    platform: cEOS
    # Pool of IPv4 addresses to configure interface Loopback0 used for BGP EVPN sessions
    loopback_ipv4_pool: 10.255.128.0/27
    # Offset all assigned loopback IP addresses.
    # Required when the < loopback_ipv4_pool > is same for 2 different node_types (like spine and l3leaf) to avoid over-lapping IPs.
    # For example, set the minimum offset l3leaf.defaults.loopback_ipv4_offset: < total # spine switches > or vice versa.
    loopback_ipv4_offset: 2
    # Definition of pool of IPs to be used as Virtual Tunnel EndPoint (VXLAN origin and destination IPs)
    vtep_loopback_ipv4_pool: 10.255.129.0/27
    # Ansible hostname of the devices used to establish neighborship (IP assignments and BGP peering)
    uplink_switches: ['dc02-spine-01', 'dc02-spine-02']
    # Definition of pool of IPs to be used in P2P links
    uplink_ipv4_pool: 10.255.255.64/26
    # Definition of pool of IPs to be used for MLAG peer-link connectivity
    mlag_peer_ipv4_pool: 10.255.129.64/27
    # iBGP Peering between MLAG peers
    mlag_peer_l3_ipv4_pool: 10.255.129.96/27
    # Virtual router mac for VNIs assigned to Leaf switches in format xx:xx:xx:xx:xx:xx
    virtual_router_mac_address: 00:1c:73:00:00:99
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp

  # If two nodes (and only two) are in the same node_group, they will automatically form an MLAG pair
  node_groups:
    # Definition of a node group that will include two devices in MLAG.
    # Definitions under the group will be inherited by both nodes in the group
    - group: DC2_L3_LEAF1
      # ASN to be used by BGP for the group. Both devices in the MLAG pair will use the same BGP ASN
      bgp_as: 65201
      nodes:
        # Definition of hostnames under the node_group
        - name: dc02-leaf-01a
          id: 11
          mgmt_ip: 172.20.20.24/24
          # Definition of the port to be used in the uplink device facing this device.
          # Note that the number of elements in this list must match the length of 'uplink_switches' as well as 'uplink_interfaces'
          uplink_switch_interfaces:
            - Ethernet1
            - Ethernet1
        - name: dc02-leaf-01b
          id: 12
          mgmt_ip: 172.20.20.25/24
          uplink_switch_interfaces:
            - Ethernet2
            - Ethernet2

    - group: DC2_BORDER_LEAF1
      bgp_as: 65202
      evpn_gateway:
        # Specific BGP EVPN Gateway functionality for route types 2 (MAC-IP), 3 (IMET) and 5 (IP-PREFIX) can be enabled separately as needed.
        evpn_l2:
          enabled: true
        evpn_l3:
          enabled: true
          inter_domain: true
      nodes:
        - name: dc02-bsl-01a
          id: 13
          mgmt_ip: 172.20.20.30/24
          uplink_switch_interfaces:
            - Ethernet5
            - Ethernet5
          evpn_gateway:
            # Define remote peers of the EVPN VXLAN Gateway.
            # If the hostname can be found in the inventory, ip_address and BGP ASN will be automatically populated.
            # Manual override takes precedence. If the peer's hostname can not be found in the inventory, ip_address and bgp_as must be defined.
            remote_peers:
              - hostname: dc01-bsl-01a
        - name: dc02-bsl-01b
          id: 14
          mgmt_ip: 172.20.20.31/24
          uplink_switch_interfaces:
            - Ethernet6
            - Ethernet6
          evpn_gateway:
            # Define remote peers of the EVPN VXLAN Gateway.
            # If the hostname can be found in the inventory, ip_address and BGP ASN will be automatically populated.
            # Manual override takes precedence. If the peer's hostname can not be found in the inventory, ip_address and bgp_as must be defined.
            remote_peers:
              - hostname: dc01-bsl-01b
